# this list is for project maintainers who update terminology
# because someone claimed to be offended or claimed that the
# terminology could be seen as offensive to a group of people.
#
# if you feel a category has been missed or a word is missing
# from the list - feel free to submit a pull request and add
# yourself to the contributors array.
#
# for those unfamiliar, the format of this document is in
# tom's obvious markup language.
# github.com/toml-lang/toml/blob/master/tests/example.toml

# words may be included in several categories. some words
# that should be in multiple catories may not be listed.
# this is considered an error, feel free to submit a
# pull request to add it to other relevant categories.

title = "wrongthink list"

[contributors]
contributors = [
  "nadya"
]

[racist]
words = [
  "abbo",
  "abeed",
  "abid",
  "alligator bait",
  "ann",
  "annamite",
  "ape",
  "apple",
  "arabush",
  "armo",
  "apache",
  "aunt jane",
  "aunt jemima",
  "aunt mary",
  "aunt sally",
  "bamboula",
  "banana",
  "beaner",
  "blacklist",
  "black sheep",
  "bluegum",
  "boche",
  "boeotian",
  "boerehater",
  "bogtrotter",
  "bohunk",
  "bong",
  "boonie",
  "bootlip",
  "bougnoule",
  "bounty bar",
  "bozgor",
  "brownie",
  "buddahead",
  "bugger",
  "bule",
  "bunga",
  "burrhead",
  "cabbage eater",
  "camel jockey",
  "chankoro",
  "charlie",
  "cheesehead",
  "chernozhopy",
  "chi-chi",
  "chilote",
  "chinaman",
  "ching chong",
  "chink",
  "choc-ice",
  "cholo",
  "chonky",
  "christ killer",
  "chug",
  "churka",
  "ciapaty",
  "cina",
  "coconut",
  "coolie",
  "coon",
  "cracker",
  "crow",
  "curry-muncher",
  "cushi",
  "dago",
  "dal khor",
  "darky",
  "dink",
  "dogan",
  "dothead",
  "dune coon",
  "eight ball",
  "eyetie",
  "fenian",
  "feuj",
  "flip",
  "fritz",
  "frog",
  "fuzzy-wuzzy",
  "gaijin",
  "gammon",
  "gans",
  "gin jockey",
  "gin",
  "ginzo",
  "golliwog",
  "gook",
  "gora",
  "goth",
  "goy",
  "greaseball",
  "greaser",
  "gringo",
  "groid",
  "gub",
  "guinea",
  "guizi",
  "gweilo",
  "gyopo",
  "gypsy",
  "hadji",
  "hairyback",
  "half-breed",
  "haole",
  "heeb",
  "hike",
  "hillbilly",
  "honky",
  "hori",
  "hun",
  "hunky",
  "hymie",
  "ikey",
  "indon",
  "injun",
  "jakun",
  "jap",
  "japie",
  "jerry",
  "jewboy",
  "jigaboo",
  "jim crow",
  "jock",
  "jungle bunny",
  "kalar",
  "kanaka",
  "kanake",
  "kano",
  "katsap",
  "kauffir",
  "kebab",
  "keling",
  "kharkhuwa",
  "khokhol",
  "kike",
  "kimchi",
  "knacker",
  "kolorad",
  "kraut",
  "kyopo",
  "labas",
  "laowai",
  "lebo",
  "limey",
  "lubra",
  "lugan",
  "mabuno",
  "macaca",
  "majus",
  "malakh-khor",
  "malaun",
  "malingsia",
  "malon",
  "mau-mau",
  "mick",
  "moon cricket",
  "moskal",
  "mulignan",
  "mzungu",
  "nawar",
  "nere",
  "niakoué",
  "nigga",
  "nigger",
  "niglet",
  "nignog",
  "nip",
  "nitchie",
  "nusayri",
  "oreo",
  "oven dodger",
  "overner",
  "paddy",
  "paki",
  "palagi",
  "paleface",
  "pancake",
  "peckerwood",
  "pepper",
  "pickaninny",
  "piefke",
  "pikey",
  "plastic paddy",
  "pocha",
  "pocho",
  "polack",
  "polaco",
  "pom",
  "porch monkey",
  "portagee",
  "pribumi",
  "pshek",
  "quashie",
  "raghead",
  "rastus",
  "razakars",
  "redlegs",
  "redneck",
  "redskin",
  "rooinek",
  "rosuke",
  "roto",
  "roundeye",
  "rusnya",
  "russki",
  "sambo",
  "sand nigger",
  "sassenach",
  "sawney",
  "scandihoovian",
  "schvartse",
  "seppo",
  "septic",
  "sheeny",
  "sheep shagger",
  "shegetz",
  "shelta",
  "shiksa",
  "shine",
  "shiptar",
  "shkije",
  "shkutzim",
  "shylock",
  "sideways vagina",
  "skinny",
  "skip",
  "skippy",
  "skopianoi",
  "slanteye",
  "slopehead",
  "smoked irish",
  "soosmar-khor",
  "sooty",
  "southern faerie",
  "soutpiel",
  "spade",
  "spearchucker",
  "spic",
  "spook",
  "squarehead",
  "squaw",
  "swamp guinea",
  "tacohead",
  "taffy",
  "taig",
  "tar-baby",
  "teapot",
  "terrone",
  "teuchter",
  "thicklips",
  "timber nigger",
  "ting tong",
  "tinker",
  "toad",
  "tork-e khar",
  "towel head",
  "turco-albanian",
  "turk",
  "twinkie",
  "ukrop",
  "uncle tom",
  "vatnik",
  "wasp",
  "west islander",
  "wetback",
  "white lie",
  "whitelist",
  "white trash",
  "whitey",
  "wigger",
  "wog",
  "wop",
  "xiao riben",
  "yam yam",
  "yank",
  "yankee",
  "yellow",
  "yid",
  "yuon",
  "zipperhead"
]

# words offensive to male, female, non-binary, gender-fluid
# gender-queer, bigender, intergender, novigender, and
# other range of genders. it encompasses the term "sexist"
# in its entirity and hopes to be fully inclusive, even of
# non-binary genders. it also includes terms that can be
# mysognistic or misandric.
[gender]
words = [
  "aggressive",
  "bae",
  "banshee",
  "becky",
  "beta male",
  "bitch",
  "bitchy",
  "black buck",
  "blonde",
  "bossy",
  "bro",
  "bubbly",
  "catty",
  "cheap",
  "cock tease",
  "cold",
  "cougar",
  "crone",
  "cunt",
  "ditzy",
  "diva",
  "dyke",
  "easy",
  "emotional",
  "feisty",
  "feminazi",
  "fishwife",
  "flirty",
  "girlie man",
  "hag",
  "harpy",
  "housewife",
  "hysterical",
  "irrational",
  "jailbait",
  "ladylike",
  "lippy",
  "loose",
  "man-hater",
  "mannish",
  "mansplain",
  "manspread",
  "manterrupting",
  "maternal",
  "mistress",
  "modest",
  "naggy",
  "neckbeard",
  "paternal",
  "prima donna",
  "princess",
  "prude",
  "queen bee",
  "sassy",
  "shrill",
  "sissy",
  "slut",
  "soccer mom",
  "spinster",
  "squaw",
  "swerf",
  "tease",
  "terf",
  "termagant",
  "tomboy",
  "tomgirl",
  "town bike",
  "tranny",
  "twat",
  "virago",
  "whimpster",
  "working mother",
  "zhyd"
]

# words that are used against the functionally diverse.
[ablist]
words = [
  "autistic",
  "blind",
  "cripple",
  "daft",
  "deformed",
  "differently abled",
  "dim",
  "downie",
  "dumb",
  "epileptic",
  "feeble-minded",
  "fit",
  "freak",
  "fucktard",
  "gimp",
  "handicapped",
  "hare lip",
  "hysterical",
  "idiot",
  "imbecile",
  "incapacitated",
  "insane",
  "invalid",
  "lame",
  "looney",
  "lunatic",
  "mad",
  "maniac",
  "midget",
  "moron",
  "mute",
  "nutter",
  "patient",
  "psycho",
  "retard",
  "schizo",
  "tard",
  "two wheels",
  "vegetable",
  "window licker",
  "yuppie flu"
]

# words that are used as slurs against heterosexuals or could
# offend heterosexual people.
[heterophobic]
words = [
  "cis",
  "cisnormal"
]

# words that are used as slurs against homosexuals or could
# offend homosexual people. this is for the lg in lgbt.
[homophobic]
words = [
  "bummer",
  "batty boy",
  "butch",
  "carpet muncher",
  "chutney ferret",
  "dike",
  "dyke",
  "fag bomb",
  "fag",
  "faggot",
  "fruit",
  "gay mafia",
  "gay",
  "meat packer",
  "pillow biter",
  "queen",
  "queer",
  "twink"
]

# words that are used as slurs against bisexuals or could
# offend bisexual people. this is for the b in lgbt.
[biphobic]
words = [
  "ac/dc",
  "ambidextrous"
]

# words that are used as slurs against transexuals or could
# offend transexual people. this is for the t in lgbt. it
# will also include slurs against gender dysphorics who
# may not consider themselves transexuals.
[transphobic]
words = [
  "tranny",
  "queer",
  "crossdresser"
]

# words that are against a group of religious people or
# that are religious and may offend agnostiscs or atheists.
[religious]
words = [
  "abe",
  "balija",
  "bible basher",
  "bible beater",
  "bible thumber",
  "clamhead",
  "creeping jesus",
  "cult",
  "fenian",
  "fundie",
  "god botherer",
  "hajji",
  "heathen",
  "hebe",
  "holly roller",
  "hymie",
  "ikey",
  "infidel",
  "jack mormon",
  "jewboy",
  "kaafir",
  "kike",
  "left-footer",
  "mackerel snapper",
  "majoos",
  "mick",
  "moch",
  "mocky",
  "mohammedan",
  "mussie",
  "orangie",
  "osama",
  "papist",
  "prod",
  "quran thumber",
  "raghead",
  "red sea pedestrian",
  "redneck",
  "russellite",
  "shaker",
  "sheeny",
  "shylock",
  "soup-taker",
  "spike",
  "taig",
  "towelhead",
  "wasp",
  "yid",
]

# words used in place of offensive words but may still offend
# people for implying the usage of an offensive word.
[euphemism]
words = [
  "thug"
]

# words that could potentionally cause someone with pstd, real
# or otherwise, harm.
[triggers]
words = [
  "abort",
  "abortion",
  "beat",
  "force",
  "harm",
  "kill",
  "rape",
  "smash",
  "suicide",
  "terminate",
  "trigger"
]

# words specifically meant to be offensive to a group of people
[pejorative]
words = [
  "abnormal",
  "absent-minded",
  "addlehead",
  "airhead",
  "american-born confused desi",
  "anchor baby",
  "angry",
  "angry white male",
  "animal epithet",
  "annoying",
  "anorak",
  "antiquarian",
  "armchair warrior",
  "arrogant",
  "ars",
  "asshole",
  "atel",
  "authoritarian",
  "autocratic",
  "baby mama",
  "baka",
  "barbarian",
  "battle-axe",
  "batty boy",
  "benny",
  "bernie bro",
  "bimbo",
  "bitch",
  "black sheep",
  "bogan",
  "bonackers",
  "boring",
  "bought priesthood",
  "breeder",
  "bridge and tunnel",
  "brigade",
  "bro",
  "bubba",
  "buckra",
  "buffoon",
  "bugger",
  "cafeteria christianity",
  "carpetbagger",
  "cat lady",
  "cave people",
  "chad",
  "chairo",
  "charlestown townies",
  "chav",
  "cheese-eating surrender monkeys",
  "chicalon",
  "chicken",
  "chickenhawk",
  "chickenhawk",
  "chilango",
  "cholo",
  "chonger",
  "city slicker",
  "club fighter",
  "coarse",
  "cocksucker",
  "condescending",
  "congenital iodine deficiency syndrome",
  "contemptuous",
  "control freak",
  "coolie",
  "coonass",
  "corn pone",
  "counter-revolutionary",
  "coward",
  "cracker",
  "crank",
  "cranky",
  "cretin",
  "cripple",
  "croppy",
  "cuckservative",
  "culchie",
  "cunt",
  "deadbeat parent",
  "dense",
  "descamisado",
  "deviant",
  "dick",
  "dictatorial",
  "dimwit",
  "dip",
  "dipshit",
  "dipwad",
  "disdainful",
  "disgusting",
  "do-gooder",
  "dogmatic",
  "dolt",
  "dresiarz",
  "dullard",
  "dumbass",
  "dunce",
  "dunderhead",
  "earthling",
  "eejit",
  "egghead",
  "egotistical",
  "emmet",
  "envious",
  "ergi",
  "essex girl",
  "essex man",
  "eurocrat",
  "eurotrash",
  "evil",
  "fag hag",
  "faggot",
  "famous for being famous",
  "fantasizer",
  "fascist",
  "fascist",
  "fatuous",
  "feeble-minded",
  "female hysteria",
  "feminazi",
  "fenian",
  "feral",
  "flamingant",
  "floozie",
  "fng syndrome",
  "fresa",
  "fresh off the boat",
  "fruit",
  "fuddy-duddy",
  "fuerdai",
  "fundie",
  "gabr",
  "gammon",
  "gauche caviar",
  "geek",
  "generation snowflake",
  "gentoo",
  "girlie men",
  "git",
  "gold bug",
  "gold miss",
  "gonk",
  "good ol' boy",
  "gopnik",
  "government mouthpiece",
  "hack writer",
  "hanjian",
  "haole",
  "happy-clappy",
  "harpy",
  "harry",
  "haughty",
  "helicopter parent",
  "heretical",
  "hillbilly",
  "himbo",
  "hipster",
  "holy roller",
  "honey dipper",
  "hoosier",
  "hori",
  "hoser",
  "hottentot",
  "house negro",
  "idiot",
  "ignorant",
  "imbecile",
  "immature",
  "immoral",
  "impulsive",
  "incompetent",
  "indian giver",
  "inept",
  "infantile",
  "inorodtsy",
  "insane",
  "insignificant",
  "internet troll",
  "irritable",
  "jackeen",
  "jafa",
  "janner",
  "jash",
  "jealous",
  "jim crow",
  "jobsworth",
  "jook-sing",
  "kaffir",
  "knacker",
  "know-it-all",
  "kulak",
  "kyōiku mama",
  "l word",
  "lamer",
  "lesbian until graduation",
  "liberal elite",
  "libertine",
  "limousine liberal",
  "line sitting",
  "little eichmanns",
  "long hair",
  "lothario",
  "lounge lizard",
  "low-life",
  "luddite",
  "lunatic",
  "lunatic fringe",
  "lunk",
  "luser",
  "mahound",
  "malinchism",
  "the man",
  "meddler",
  "meff",
  "middle australia",
  "middle england",
  "misogynist",
  "mleccha",
  "mockney",
  "moll",
  "mongoloid",
  "moron",
  "mother's boy",
  "motherfucker",
  "mouth breather",
  "mundane",
  "nabob",
  "naco",
  "naive",
  "nakusha",
  "napoleon complex",
  "neckbeard",
  "ned",
  "nerd",
  "neurotic",
  "newfie",
  "nigger",
  "nimby",
  "nincompoop",
  "ninny",
  "nonsensical",
  "nouveau poor",
  "nouveau riche",
  "nowhere girls",
  "oaf",
  "obrazovanshchina",
  "ocker",
  "oholah and oholibah",
  "okie",
  "otaku",
  "out of touch",
  "parasitism",
  "partitionism",
  "party pooper",
  "peckerwood",
  "pedant",
  "pendatang asing",
  "peon",
  "pessimistic",
  "philistinism",
  "pikey",
  "piney",
  "pinko",
  "plant epithet",
  "plastic brit",
  "plastic paddy",
  "plucky brit",
  "plyg",
  "pocho",
  "podkulachnik",
  "pogue",
  "political hack",
  "poodle",
  "poseur",
  "prawn sandwich brigade",
  "prick",
  "prig",
  "prude",
  "puddle pirate",
  "quisling",
  "race traitor",
  "radical chic",
  "rah",
  "razakar",
  "redneck",
  "republicrat",
  "retard",
  "rhineland bastard",
  "rhodie",
  "ridiculous",
  "rootless cosmopolitan",
  "rube",
  "samosely",
  "sarong party girl",
  "schemie",
  "schmo",
  "schmuck",
  "schvartze",
  "script kiddie",
  "selfish",
  "sexual predator",
  "sheeple",
  "sheltered",
  "shemale",
  "sheng nu",
  "shiksa",
  "shoddy millionaires",
  "shoneenism",
  "shoobie",
  "shrew",
  "shyster",
  "simpleton",
  "sissy",
  "skeet",
  "slacktivism",
  "slut",
  "snob",
  "snowflake",
  "social justice warrior",
  "softy",
  "space cadet",
  "spanish unionism",
  "spastic",
  "spinster",
  "square",
  "squaw",
  "stupid",
  "stupid fuck",
  "stupidhead",
  "sucker",
  "suppressive person",
  "suzy homemaker",
  "swamp yankee",
  "swine",
  "tai ke",
  "tard",
  "teabagging",
  "teuchter",
  "titushky",
  "tomato can",
  "tomfool",
  "tosspot",
  "totalitarian",
  "trailer trash",
  "tranny",
  "trixie",
  "troll",
  "trophy wife",
  "tuhao",
  "twat",
  "twink",
  "twinkie",
  "u word",
  "ugly american",
  "un-australian",
  "uncle tom",
  "unconventional",
  "uncool",
  "undesirable",
  "uninteresting",
  "unpleasant",
  "unrefined",
  "untermensch",
  "useful idiot",
  "vacuous",
  "vapid",
  "vatnik",
  "village idiot",
  "virago",
  "vulture capitalist",
  "w word",
  "wabenzi",
  "wacko",
  "walter mitty",
  "wanker",
  "wasi'chu",
  "welfare queen",
  "west brit",
  "westie",
  "wetback",
  "worthless",
  "wowser",
  "xarnego",
  "yahoo",
  "yob",
  "yobaz",
  "yokel",
  "yordim",
  "yuppie",
  "zhyd",
  "zindīq"
]

# words that could potentially offend someone for historical
# uses of the words.
[historical]
words = [
  "master",
  "slave"
]
